---
date: "`r Sys.Date()`"
title: "All WR SIT DSM Summary Tables - BA Act5"
output: 
  officedown::rdocx_document:
        reference_docx: C:/Users/avaisvil/OneDrive - DOI/Documents/LTO Modeling/SIT-DSM-LTO/TableTemplate.docx
        tables:
          style: StyleAlpha
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
require(officedown)
require(officer)
require(readr)
require(here)
```

```{r, echo=FALSE}
# Function to calculate percent differences and append to the table
calculate_percent_diff <- function(table){
  for(i in 4:ncol(table)){
    table[, i] <- paste0(table[, i], " (", round(((table[, i] - table[, 3]) / table[, 3]) * 100, 1), ")")
  }
  return(table)
}
```

##### '
## BA 

### Population Abundance, Growth

```{r tab.cap="Table BA.1. Predicted annual total winter-run spawner abundance in the Upper Sacramento River, including both natural- and hatchery-origin fish.", tab.id="TableBA1", echo=FALSE}
table1 <- read.csv(here(paste0("winterRunDSM-Main/Output/Tables/BA_AllSpawnersAct5.csv")))
colnames(table1) <- gsub("."," ", colnames(table1), fixed=TRUE)
table1 <- round(table1)
#table1 <- calculate_percent_diff(table1)
table1
```

##### '

```{r tab.cap="Table BA.2. Predicted annual natural-origin winter-run spawner abundance in the Upper Sacramento River.", tab.id="TableBA2", echo=FALSE}
table2 <- read.csv(here(paste0("winterRunDSM-Main/Output/Tables/BA_NatSpawnersAct5.csv")))
colnames(table2) <- gsub("."," ", colnames(table2), fixed=TRUE)
table2 <- round(table2)
table2
```

##### '

```{r tab.cap="Table BA.3. Predicted mean lambda (Nt+1/Nt) for total winter-run spawner abundance in the Upper Sacramento River, including both natural- and hatchery-origin fish.", tab.id="TableBA3", echo=FALSE}
table3 <- read.csv(here(paste0("winterRunDSM-Main/Output/Tables/BA_MeanLambdaAct5.csv")))
table3$WYT <- "All"

mlambda_wyt <- read.csv(here(paste0("winterRunDSM-Main/Output/Tables/BA_WYTMeanLambdaAct5.csv")))
table3 <- rbind(mlambda_wyt, table3)

colnames(table3) <- gsub("."," ", colnames(table3), fixed=TRUE)
table3[,2:length(table3)] <- round(table3[,2:length(table3)], 3)
table3
```

##### '

```{r tab.cap="Table BA.4. Predicted terminal lambda (Nt=19/Nt=1) for total winter-run spawner abundance in the Upper Sacramento River, including both natural- and hatchery-origin fish, from deterministic model runs.", tab.id="TableBA4", echo=FALSE}
table4 <- read.csv(here(paste0("winterRunDSM-Main/Output/Tables/BA_EndLambdaAct5.csv")))
colnames(table4) <- gsub("."," ", colnames(table4), fixed=TRUE)
table4 <- round(table4, 3)
table4
```


##### '

##### '
##### ' 
### Demographic Parameters

```{r tab.cap="Table BA.5. Predicted small juvenile rearing survival for winter-run Chinook salmon in the Upper Sacramento River.", tab.id="TableBA5", echo=FALSE}
table5 <- read.csv(here(paste0("winterRunDSM-Main/Output/Tables/BA_SRearUSRAct5.csv")))
colnames(table5) <- gsub("."," ", colnames(table5), fixed=TRUE)
table5[,3:9] <- round(table5[,3:9], 3)
table5
```
##### ' 

```{r tab.cap="Table BA.6. Predicted smolt migratory survival for winter-run Chinook salmon in the Upper-mid Sacramento River.", tab.id="TableBA6", echo=FALSE}
table6 <- read.csv(here(paste0("winterRunDSM-Main/Output/Tables/BA_VLMigrUMAct5.csv")))
colnames(table6) <- gsub("."," ", colnames(table6), fixed=TRUE)
table6[,3:9] <- round(table6[,3:9], 3)
table6
```
##### ' 

```{r tab.cap="Table BA.7. Predicted smolt migratory survival for winter-run Chinook salmon in the Lower-mid Sacramento River.", tab.id="TableBA7", echo=FALSE}
table7 <- read.csv(here(paste0("winterRunDSM-Main/Output/Tables/BA_VLMigrLMAct5.csv")))
colnames(table7) <- gsub("."," ", colnames(table7), fixed=TRUE)
table7[,3:9] <- round(table7[,3:9], 3)
table7
```

##### '
```{r tab.cap="Table BA.8. Predicted smolt migratory survival for winter-run Chinook salmon in the Lower Sacramento River.", tab.id="TableBA8", echo=FALSE}
table8 <- read.csv(here(paste0("winterRunDSM-Main/Output/Tables/BA_VLMigrLLAct5.csv")))
colnames(table8) <- gsub("."," ", colnames(table8), fixed=TRUE)
table8[,3:9] <- round(table8[,3:9], 2)
table8
```

##### '
```{r tab.cap="Table BA.9. Predicted smolt migratory survival for winter-run Chinook salmon in the North Delta.", tab.id="TableBA9", echo=FALSE}
table9 <- read.csv(here(paste0("winterRunDSM-Main/Output/Tables/BA_VLMigrNDeltaAct5.csv")))
colnames(table9) <- gsub("."," ", colnames(table9), fixed=TRUE)
table9[,3:9] <- round(table9[,3:9], 3)
table9
```

##### '
```{r tab.cap="Table BA.10. Predicted smolt migratory survival for winter-run Chinook salmon in the South Delta.", tab.id="TableBA10", echo=FALSE}
table10 <- read.csv(here(paste0("winterRunDSM-Main/Output/Tables/BA_VLMigrSDeltaAct5.csv")))
colnames(table10) <- gsub("."," ", colnames(table10), fixed=TRUE)
table10[,3:9] <- round(table10[,3:9], 3)
table10
```
##### '


