---
date: "`r Sys.Date()`"
title: "All WR SIT DSM Summary Tables - EIS"
output: 
  officedown::rdocx_document:
        reference_docx: C:/Users/ajensen/OneDrive - DOI/Documents/Science Division/R resources/TableTemplate.docx
        tables:
          style: StyleAlpha
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
require(officedown)
require(officer)
require(readr)
require(here)
```


##### '
## EIS 

### Population Abundance, Growth

```{r tab.cap="Table EIS.1. Predicted annual total winter-run spawner abundance in the Upper Sacramento River, including both natural- and hatchery-origin fish.", tab.id="TableEIS1", echo=FALSE}
table1 <- read.csv(here(paste0("winterRunDSM-Main/Output/Tables/EIS_AllSpawners.csv")))
colnames(table1) <- gsub("."," ", colnames(table1), fixed=TRUE)
table1 <- round(table1)
table1
```
##### '
```{r tab.cap="Table EIS.1b. Predicted percent differences in annual total winter-run spawner abundance in the Upper Sacramento River, including both natural- and hatchery-origin fish, relative to NAA.", tab.id="TableEIS1b", echo=FALSE}
table1b <- read.csv(here(paste0("winterRunDSM-Main/Output/Tables/EIS_AllSpawnersPercDiff.csv")))
colnames(table1b) <- gsub("."," ", colnames(table1b), fixed=TRUE)
table1b <- round(table1b,2)
table1b
```

##### '

```{r tab.cap="Table EIS.2. Predicted annual natural-origin winter-run spawner abundance in the Upper Sacramento River.", tab.id="TableEIS2", echo=FALSE}
table2 <- read.csv(here(paste0("winterRunDSM-Main/Output/Tables/EIS_NatSpawners.csv")))
colnames(table2) <- gsub("."," ", colnames(table2), fixed=TRUE)
table2 <- round(table2)
table2
```
##### '
```{r tab.cap="Table EIS.2b. Predicted percent difference in annual natural-origin winter-run spawner abundance in the Upper Sacramento River, relative to NAA.", tab.id="TableEIS2b", echo=FALSE}
table2b <- read.csv(here(paste0("winterRunDSM-Main/Output/Tables/EIS_NatSpawnersPercDiff.csv")))
colnames(table2b) <- gsub("."," ", colnames(table2b), fixed=TRUE)
table2b <- round(table2b,2)
table2b
```

##### '

```{r tab.cap="Table EIS.3. Predicted mean lambda (Nt+1/Nt) for total winter-run spawner abundance in the Upper Sacramento River, including both natural- and hatchery-origin fish.", tab.id="TableEIS3", echo=FALSE}
table3 <- read.csv(here(paste0("winterRunDSM-Main/Output/Tables/EIS_MeanLambda.csv")))
table3$WYT <- "All"

mlambda_wyt <- read.csv(here(paste0("winterRunDSM-Main/Output/Tables/EIS_WYTMeanLambda.csv")))
table3 <- rbind(mlambda_wyt, table3)

colnames(table3) <- gsub("."," ", colnames(table3), fixed=TRUE)
table3[,2:length(table3)] <- round(table3[,2:length(table3)], 3)
table3
```
##### '
```{r tab.cap="Table EIS.3b. Predicted percent difference in mean lambda (Nt+1/Nt) for total winter-run spawner abundance in the Upper Sacramento River, including both natural- and hatchery-origin fish, relative to NAA.", tab.id="TableEIS3b", echo=FALSE}
table3b <- read.csv(here(paste0("winterRunDSM-Main/Output/Tables/EIS_MeanLambdaPercDiff.csv")))
table3b$WYT <- "All"

mlambda_wyt <- read.csv(here(paste0("winterRunDSM-Main/Output/Tables/EIS_WYTMeanLambdaPercDiff.csv")))
table3b <- rbind(mlambda_wyt, table3b)

colnames(table3b) <- gsub("."," ", colnames(table3b), fixed=TRUE)
table3b[,2:length(table3b)] <- round(table3b[,2:length(table3b)], 2)
table3b
```

##### '

```{r tab.cap="Table EIS.4. Predicted terminal lambda (Nt=19/Nt=1) for total winter-run spawner abundance in the Upper Sacramento River, including both natural- and hatchery-origin fish, from deterministic model runs.", tab.id="TableEIS4", echo=FALSE}
table4 <- read.csv(here(paste0("winterRunDSM-Main/Output/Tables/EIS_EndLambda.csv")))
colnames(table4) <- gsub("."," ", colnames(table4), fixed=TRUE)
table4 <- round(table4, 3)
table4
```
##### '
```{r tab.cap="Table EIS.4b. Predicted percent difference in terminal lambda (Nt=19/Nt=1) for total winter-run spawner abundance in the Upper Sacramento River, including both natural- and hatchery-origin fish, from deterministic model runs relative to NAA.", tab.id="TableEIS4b", echo=FALSE}
table4b <- read.csv(here(paste0("winterRunDSM-Main/Output/Tables/EIS_EndLambdaPercDiff.csv")))
colnames(table4b) <- gsub("."," ", colnames(table4b), fixed=TRUE)
table4b <- round(table4b, 2)
table4b
```

##### '

##### '
##### ' 
### Demographic Parameters

```{r tab.cap="Table EIS.5. Predicted small juvenile rearing survival for winter-run Chinook salmon in the Upper Sacramento River.", tab.id="TableEIS5", echo=FALSE}
table5 <- read.csv(here(paste0("winterRunDSM-Main/Output/Tables/EIS_SRearUSR.csv")))
colnames(table5) <- gsub("."," ", colnames(table5), fixed=TRUE)
table5[,3:9] <- round(table5[,3:9], 3)
table5
```
##### ' 

```{r tab.cap="Table EIS.6. Predicted smolt migratory survival for winter-run Chinook salmon in the Upper-mid Sacramento River.", tab.id="TableEIS6", echo=FALSE}
table6 <- read.csv(here(paste0("winterRunDSM-Main/Output/Tables/EIS_VLMigrUM.csv")))
colnames(table6) <- gsub("."," ", colnames(table6), fixed=TRUE)
table6[,3:9] <- round(table6[,3:9], 3)
table6
```
##### ' 

```{r tab.cap="Table EIS.7. Predicted smolt migratory survival for winter-run Chinook salmon in the Lower-mid Sacramento River.", tab.id="TableEIS7", echo=FALSE}
table7 <- read.csv(here(paste0("winterRunDSM-Main/Output/Tables/EIS_VLMigrLM.csv")))
colnames(table7) <- gsub("."," ", colnames(table7), fixed=TRUE)
table7[,3:9] <- round(table7[,3:9], 3)
table7
```

##### '
```{r tab.cap="Table EIS.8. Predicted smolt migratory survival for winter-run Chinook salmon in the Lower Sacramento River.", tab.id="TableEIS8", echo=FALSE}
table8 <- read.csv(here(paste0("winterRunDSM-Main/Output/Tables/EIS_VLMigrLL.csv")))
colnames(table8) <- gsub("."," ", colnames(table8), fixed=TRUE)
table8[,3:9] <- round(table8[,3:9], 2)
table8
```

##### '
```{r tab.cap="Table EIS.9. Predicted smolt migratory survival for winter-run Chinook salmon in the North Delta.", tab.id="TableEIS9", echo=FALSE}
table9 <- read.csv(here(paste0("winterRunDSM-Main/Output/Tables/EIS_VLMigrNDelta.csv")))
colnames(table9) <- gsub("."," ", colnames(table9), fixed=TRUE)
table9[,3:9] <- round(table9[,3:9], 3)
table9
```

##### '
```{r tab.cap="Table EIS.10. Predicted smolt migratory survival for winter-run Chinook salmon in the South Delta.", tab.id="TableEIS10", echo=FALSE}
table10 <- read.csv(here(paste0("winterRunDSM-Main/Output/Tables/EIS_VLMigrSDelta.csv")))
colnames(table10) <- gsub("."," ", colnames(table10), fixed=TRUE)
table10[,3:9] <- round(table10[,3:9], 3)
table10
```
##### '


